const state={inventory:[],recipes:[],products:[],units:[],view:"inicio"};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const config=window.CALDERO_CONFIG||{};let apiUrl=(localStorage.getItem("caldero_api_url")??config.defaultApiUrl??"").replace(/\/$/,"");
let accessPin=sessionStorage.getItem("caldero_access_pin")||"";
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const normalizeText=value=>String(value??"").trim().toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g,"");
async function api(path,options={}){const response=await fetch(`${apiUrl}${path}`,{headers:{"Content-Type":"application/json",...(accessPin?{"X-Caldero-Pin":accessPin}:{}),...(options.headers||{})},...options});const body=await response.json().catch(()=>({}));if(!response.ok){if(response.status===401){setTimeout(()=>openSettings(true),0);throw new Error("Código de acceso requerido o incorrecto.")}throw new Error(body.error||`Error ${response.status}`)}return body}
function notify(message,type="success"){const el=$("#notice");el.textContent=message;el.className=`notice ${type}`;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.add("hidden"),5000)}
function setConnection(online){const pill=$("#connection-pill");pill.className=`connection-pill ${online?"online":"offline"}`;$("b",pill).textContent=online?"Conectado":"Sin conexión"}
function empty(){return $("#empty-template").content.cloneNode(true)}
function initials(name){return name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function expiryLabel(item){if(item.expired)return ["Vencido","expired"];if(item.days_until_expiration===0)return ["Vence hoy","urgent"];if(item.days_until_expiration<=3)return [`${item.days_until_expiration} días`,"urgent"];return [new Date(`${item.expiration_date}T12:00:00`).toLocaleDateString("es-PR",{month:"short",day:"numeric"}),""]}
function recipeCard(recipe){const ready=recipe.availability?.can_prepare;const missing=recipe.availability?.missing||[];const article=document.createElement("article");article.className=`recipe-card ${ready?"ready":"missing"}`;article.innerHTML=`<div class="card-top"><span class="tag">${escapeHtml(recipe.category||"Receta")}</span><span class="status ${ready?"ok":"warn"}">${ready?"✓ Puedes preparar":`${missing.length} por conseguir`}</span></div><h3>${escapeHtml(recipe.name)}</h3><p>${escapeHtml(recipe.description||recipe.instructions||"")}</p><footer><span>${recipe.ingredients?.length||0} ingredientes</span><button class="text-button" data-recipe="${recipe.id}">${ready?"Preparar":"Ver faltantes"} →</button></footer>`;return article}
function renderInventory(){const list=$("#inventory-list");list.innerHTML="";const term=$("#inventory-search").value.trim().toLowerCase();const filter=$("#inventory-filter").value;const items=state.inventory.filter(item=>(!term||item.name.toLowerCase().includes(term))&&(filter==="all"||(filter==="urgent"&&!item.expired&&item.days_until_expiration<=3)||(filter==="leftover"&&item.source==="leftover")));if(!items.length){list.append(empty());return}items.forEach(item=>{const [label,klass]=expiryLabel(item);const row=document.createElement("article");row.className="inventory-row";row.innerHTML=`<span class="food-avatar">${initials(item.name)}</span><div><strong>${escapeHtml(item.name)}</strong><small>${item.source==="leftover"?"Sobra reutilizable":"Inventario"}</small></div><div class="category"><strong>${escapeHtml(item.category||"Sobra")}</strong><small>Categoría</small></div><div class="quantity"><strong>${item.quantity} ${escapeHtml(item.unit)}</strong><small>Disponible</small></div><span class="expiry ${klass}">${label}</span>`;list.append(row)})}
function renderRecipes(){const list=$("#recipe-list");const home=$("#home-recipes");list.innerHTML="";home.innerHTML="";const term=$("#recipe-search").value.trim().toLowerCase();const filter=$("#recipe-filter").value;const recipes=state.recipes.filter(recipe=>(!term||recipe.name.toLowerCase().includes(term))&&(filter==="all"||(filter==="ready"&&recipe.availability.can_prepare)||(filter==="missing"&&!recipe.availability.can_prepare)));if(!recipes.length)list.append(empty());recipes.forEach(recipe=>list.append(recipeCard(recipe)));state.recipes.slice(0,3).forEach(recipe=>home.append(recipeCard(recipe)));const select=$("#leftover-recipe");select.innerHTML=state.recipes.map(recipe=>`<option value="${recipe.id}">${escapeHtml(recipe.name)}</option>`).join("")}
function renderLeftovers(){const list=$("#leftover-list");list.innerHTML="";const leftovers=state.inventory.filter(item=>item.source==="leftover");if(!leftovers.length){list.append(empty());return}leftovers.forEach(item=>{const [label,klass]=expiryLabel(item);const card=document.createElement("article");card.className="leftover-card";card.innerHTML=`<span class="tag">Reutilizable</span><h3>${escapeHtml(item.name)}</h3><p>${item.quantity} ${escapeHtml(item.unit)}</p><span class="expiry ${klass}">${label}</span>`;list.append(card)})}
function renderSummary(){const active=state.inventory.filter(item=>!item.expired);const ready=state.recipes.filter(recipe=>recipe.availability.can_prepare);const leftovers=active.filter(item=>item.source==="leftover");$("#stat-inventory").textContent=active.length;$("#stat-recipes").textContent=ready.length;$("#stat-leftovers").textContent=leftovers.length;const urgent=active[0];$("#urgent-title").textContent=urgent?`${urgent.name} vence ${urgent.days_until_expiration===0?"hoy":"pronto"}`:"Tu inventario está al día";$("#urgent-copy").textContent=urgent?`Tienes ${urgent.quantity} ${urgent.unit}. Mira qué receta puede aprovecharlo primero.`:"Registra un alimento para comenzar."}
async function loadData(){try{const data=await api("/api/bootstrap");state.inventory=data.inventory.items;state.recipes=data.recipes.recipes;state.products=data.catalog.products;state.units=data.catalog.units;setConnection(true);$("#product-options").innerHTML=state.products.map(item=>`<option value="${escapeHtml(item.name)}">`).join("");$("#unit-options").innerHTML=state.units.map(unit=>`<option value="${escapeHtml(unit)}">`).join("");renderInventory();renderRecipes();renderLeftovers();renderSummary()}catch(error){setConnection(false);notify(`No pudimos conectar con ${apiUrl||"el backend de Caldero Verde"}. Abre Configurar conexión para revisar los datos.`,"error");["#inventory-list","#recipe-list","#home-recipes","#leftover-list"].forEach(id=>{$(id).innerHTML="";$(id).append(empty())})}}
function showView(view){state.view=view;$$('.view').forEach(el=>el.classList.toggle("active",el.id===`view-${view}`));$$('.nav-link').forEach(el=>el.classList.toggle("active",el.dataset.view===view));const titles={inicio:"¿Qué podemos aprovechar hoy?",inventario:"Todo empieza con lo que tienes",recetas:"Cocina sin desperdiciar",sobras:"Dale otra vuelta a tus sobras"};$("#page-title").textContent=titles[view];location.hash=view;$(".sidebar").classList.remove("open")}
async function submitForm(form,path){const data=Object.fromEntries(new FormData(form));data.quantity=Number(data.quantity);try{const button=$("button[type=submit]",form);button.disabled=true;await api(path,{method:"POST",body:JSON.stringify(data)});form.reset();form.classList.add("hidden");notify("Guardado correctamente.");await loadData()}catch(error){notify(error.message,"error")}finally{const button=$("button[type=submit]",form);button.disabled=false}}
document.addEventListener("click",async event=>{const nav=event.target.closest("[data-view]");if(nav){event.preventDefault();showView(nav.dataset.view)}const go=event.target.closest("[data-go]");if(go)showView(go.dataset.go);const recipeButton=event.target.closest("[data-recipe]");if(recipeButton){const recipe=state.recipes.find(item=>String(item.id)===recipeButton.dataset.recipe);if(!recipe)return;if(!recipe.availability.can_prepare){notify(recipe.availability.missing.map(item=>`${item.ingredient}: faltan ${item.missing} ${item.unit}`).join(" · "),"error");return}if(confirm(`¿Preparar ${recipe.name}? Se descontarán los ingredientes del inventario.`)){try{await api(`/api/recipes/${recipe.id}/prepare`,{method:"POST"});notify("Receta preparada. Inventario actualizado.");await loadData()}catch(error){notify(error.message,"error")}}}const close=event.target.closest("[data-close-form]");if(close)$("#"+close.dataset.closeForm).classList.add("hidden")});
$("#toggle-product-form").onclick=()=>$("#product-form").classList.toggle("hidden");$("#toggle-leftover-form").onclick=()=>$("#leftover-form").classList.toggle("hidden");$("#product-form").onsubmit=event=>{event.preventDefault();submitForm(event.currentTarget,"/api/inventory")};$("#leftover-form").onsubmit=event=>{event.preventDefault();submitForm(event.currentTarget,"/api/leftovers")};$("#inventory-search").oninput=renderInventory;$("#inventory-filter").onchange=renderInventory;$("#recipe-search").oninput=renderRecipes;$("#recipe-filter").onchange=renderRecipes;$("#mobile-menu").onclick=()=>$(".sidebar").classList.toggle("open");
const productName=$("#product-form [name=name]");productName.onchange=()=>{const selected=state.products.find(item=>normalizeText(item.name)===normalizeText(productName.value)||(item.aliases||[]).some(alias=>normalizeText(alias)===normalizeText(productName.value)));if(!selected)return;const category=$("#product-form [name=category]");const unit=$("#product-form [name=unit]");if(!category.value)category.value=selected.category;if(!unit.value)unit.value=selected.default_unit};
const dialog=$("#settings-dialog");function openSettings(focusPin=false){$("#api-url").value=apiUrl;$("#access-pin").value=accessPin;dialog.showModal();if(focusPin)$("#access-pin").focus()}$("#open-settings").onclick=()=>openSettings();$("#save-settings").onclick=event=>{event.preventDefault();apiUrl=$("#api-url").value.trim().replace(/\/$/,"");accessPin=$("#access-pin").value.trim();if(apiUrl)localStorage.setItem("caldero_api_url",apiUrl);else localStorage.removeItem("caldero_api_url");if(accessPin)sessionStorage.setItem("caldero_access_pin",accessPin);else sessionStorage.removeItem("caldero_access_pin");dialog.close();loadData()};
const initial=(location.hash||"#inicio").slice(1);showView(["inicio","inventario","recetas","sobras"].includes(initial)?initial:"inicio");loadData();
